---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    author: Gangadhar
spec:
  containers:
    - name: my-pod1
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 9090
...
