apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deployment
  labels:
    name: redis-app
    author: Gangadhar
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-app  
  template:
    metadata:
      labels:
        name: redis-app 
    spec:
      containers:
        - name: redis 
          image: redis 

