apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: result-app
    author: Gangadhar
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-app 
  template:
    metadata:
      labels:
        name: result-app 
    spec:
      containers:
        - name: result-app-container 
          image: docker/example-voting-app-result

