apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    name: voting-app
    author: Gangadhar
spec:
  replicas: 2
  selector:
    matchLabels:
      name: voting-app
  template:
    metadata:
      labels:
        name: voting-app
    spec:
      containers:
        - name: voting-app-container 
          image: docker/example-voting-app-vote

