apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app
    author: Gangadhar
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app 
  template:
    metadata:
      labels:
        name: worker-app
    spec:
      containers:
        - name: worker-app-container  
          image: docker/example-voting-app-worker

